### ISSUE TITLE
pS 3.4.2 and 3.5 - regular testing service initiation of bwctl tests -B option

### ISSUE THREAD

**Issue by igarny** [perfsonar/regular-testing#10]
Hi

Please review an issue I see with throughput tests on an toolkit instance participating in a mesh.

Regular_testing.conf is:
<test>
    <parameters>
        tool   iperf3
        omit_interval   5
        type   bwctl
        duration   30
        force_ipv4   1
    </parameters>
    target   psmp-gn-bw-02-fra-de.geant.net
    target   ppsmp-tst-01.dub.ie.geant.net.
    local_address   psmp-tst-02.dub.ie.geant.net
    added_by_mesh   1
    description   ------------------------------------------
    <schedule>
        type   regular_intervals
        interval   10800
    </schedule>
</test>
<test>
    <parameters>
        type   powstream
        force_ipv4   1
    </parameters>
    target   psmp-gn-owd-02.fra.de.geant.net
    target   ppsmp-tst-01.dub.ie.geant.net.
    local_address   psmp-tst-02.dub.ie.geant.net
    added_by_mesh   1
    description   -----------------------------------------
    <schedule>
        type   streaming
    </schedule>
</test>
<test>
    <parameters>
        type   powstream
    </parameters>
    target   psmp-gn-owd-02.fra.de.geant.net
    target   ppsmp-tst-01.dub.ie.geant.net.
    local_address   psmp-tst-02.dub.ie.geant.net
    added_by_mesh   1
    description   ----------------------------------------------
    <schedule>
        type   streaming
    </schedule>
</test>
<test>
    <parameters>
        packet_length   40
        packet_max_ttl   64
        type   bwtraceroute
    </parameters>
    target   psmp-gn-bw-02-fra-de.geant.net
    target   ppsmp-tst-01.dub.ie.geant.net.
    local_address   psmp-tst-02.dub.ie.geant.net
    added_by_mesh   1
    description   ------------------------------------------------
    <schedule>
        type   regular_intervals
        interval   1200
    </schedule>
</test>

The related processes are:

$ ps ax | grep regular_testing
 9758 ?        S      0:00 /usr/bin/bwctl -s psmp-tst-02.dub.ie.geant.net -c psmp-gn-bw-02-fra-de.geant.net -T iperf3 -4 -I 10800 -p -d /var/lib/perfsonar/regular_testing/bwctl_VvdmJ -v -P 1 -t 30 -O 5 -i 1 --parsable
 9759 ?        S      0:01 /usr/bin/powstream -4 -p -d /var/lib/perfsonar/regular_testing/owamp_V7p_Z -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net psmp-gn-owd-02.fra.de.geant.net
 9761 ?        S      0:02 /usr/bin/powstream -4 -p -d /var/lib/perfsonar/regular_testing/owamp_UHTuc -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net -t psmp-gn-owd-02.fra.de.geant.net
 9762 ?        S      0:00 /usr/bin/bwctl -s psmp-gn-bw-02-fra-de.geant.net -c psmp-tst-02.dub.ie.geant.net -T iperf3 -4 -I 10800 -p -d /var/lib/perfsonar/regular_testing/bwctl_gX3hJ -v -P 1 -t 30 -O 5 -i 1 --parsable
 9764 ?        S      0:01 /usr/bin/powstream -p -d /var/lib/perfsonar/regular_testing/owamp_mdyBu -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net psmp-gn-owd-02.fra.de.geant.net
 9765 ?        S      0:00 /usr/bin/powstream -4 -p -d /var/lib/perfsonar/regular_testing/owamp_E414j -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net ppsmp-tst-01.dub.ie.geant.net.
 9766 ?        S      0:00 /usr/bin/bwctl -s psmp-tst-02.dub.ie.geant.net -c ppsmp-tst-01.dub.ie.geant.net. -T iperf3 -4 -I 10800 -p -d /var/lib/perfsonar/regular_testing/bwctl_z2rlM -v -P 1 -t 30 -O 5 -i 1 --parsable
 9767 ?        S      0:02 /usr/bin/powstream -p -d /var/lib/perfsonar/regular_testing/owamp_OA3iO -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net -t psmp-gn-owd-02.fra.de.geant.net
 9768 ?        S      0:00 /usr/bin/powstream -4 -p -d /var/lib/perfsonar/regular_testing/owamp_RFKrx -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net -t ppsmp-tst-01.dub.ie.geant.net.
 9769 ?        S      0:00 /usr/bin/bwctl -s ppsmp-tst-01.dub.ie.geant.net. -c psmp-tst-02.dub.ie.geant.net -T iperf3 -4 -I 10800 -p -d /var/lib/perfsonar/regular_testing/bwctl_xpH9l -v -P 1 -t 30 -O 5 -i 1 --parsable
 9770 ?        S      0:00 /usr/bin/powstream -p -d /var/lib/perfsonar/regular_testing/owamp_TYJiR -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net ppsmp-tst-01.dub.ie.geant.net.
 9771 ?        S      0:00 /usr/bin/bwtraceroute -s psmp-tst-02.dub.ie.geant.net -c psmp-gn-bw-02-fra-de.geant.net -T tracepath,traceroute -I 1200 -p -d /var/lib/perfsonar/regular_testing/bwctl_waW1G -v -M 64 -l 40 -y a -E
 9772 ?        S      0:00 /usr/bin/powstream -p -d /var/lib/perfsonar/regular_testing/owamp_IKB6h -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net -t ppsmp-tst-01.dub.ie.geant.net.
 9774 ?        S      0:00 /usr/bin/bwtraceroute -s psmp-tst-02.dub.ie.geant.net -c psmp-gn-owd-02.fra.de.geant.net -T tracepath,traceroute -I 1200 -p -d /var/lib/perfsonar/regular_testin /bwctl_IS5zD -v -M 64 -l 40 -y a -E
 9775 ?        S      0:00 /usr/bin/bwtraceroute -s psmp-gn-bw-02-fra-de.geant.net -c psmp-tst-02.dub.ie.geant.net -T tracepath,traceroute -I 1200 -p -d /var/lib/perfsonar/regular_testing/bwctl_zhK9l -v -M 64 -l 40 -y a
 9777 ?        S      0:00 /usr/bin/bwtraceroute -s psmp-tst-02.dub.ie.geant.net -c ppsmp-tst-01.dub.ie.geant.net. -T tracepath,traceroute -I 1200 -p -d /var/lib/perfsonar/regular_testing/bwctl_qfzfx -v -M 64 -l 40 -y a -E
 9778 ?        S      0:00 /usr/bin/bwtraceroute -s psmp-gn-owd-02.fra.de.geant.net -c psmp-tst-02.dub.ie.geant.net -T tracepath,traceroute -I 1200 -p -d /var/lib/perfsonar/regular_testin /bwctl_RNddm -v -M 64 -l 40 -y a
 9779 ?        S      0:00 /usr/bin/bwtraceroute -s ppsmp-tst-01.dub.ie.geant.net. -c psmp-tst-02.dub.ie.geant.net -T tracepath,traceroute -I 1200 -p -d /var/lib/perfsonar/regular_testing/bwctl_SDHPX -v -M 64 -l 40 -y a
42644 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/perfsonar/regular_testing/owamp_OA3iO -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net -t psmp-gn-owd-02.fra.de.geant.net
42671 ?        Ss     0:00 /usr/bin/powstream -4 -p -d /var/lib/perfsonar/regular_testing/owamp_V7p_Z -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net psmp-gn-owd-02.fra.de.geant.net
42690 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/perfsonar/regular_testing/owamp_mdyBu -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net psmp-gn-owd-02.fra.de.geant.net
42701 ?        Ss     0:00 /usr/bin/powstream -4 -p -d /var/lib/perfsonar/regular_testing/owamp_UHTuc -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net -t psmp-gn-owd-02.fra.de.geant.net
42731 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/perfsonar/regular_testing/owamp_OA3iO -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net -t psmp-gn-owd-02.fra.de.geant.net
42740 ?        Ss     0:00 /usr/bin/powstream -4 -p -d /var/lib/perfsonar/regular_testing/owamp_V7p_Z -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net psmp-gn-owd-02.fra.de.geant.net
42764 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/perfsonar/regular_testing/owamp_mdyBu -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net psmp-gn-owd-02.fra.de.geant.net
42784 ?        Ss     0:00 /usr/bin/powstream -4 -p -d /var/lib/perfsonar/regular_testing/owamp_UHTuc -c 600 -i 0.1 -S psmp-tst-02.dub.ie.geant.net -t psmp-gn-owd-02.fra.de.geant.net
42807 pts/0    S+     0:00 grep regular_testing

BUT the throughput tests are failing, because the tests are attempted through the default route. My finding is that the –B option is missing

$ /usr/bin/bwctl -s 62.40.123.106 -B 62.40.123.106 -c 62.40.106.83  -T iperf3 -4
bwctl: Using tool: iperf3
bwctl: 32 seconds until test results available

SENDER START
Connecting to host 62.40.106.83, port 5496
[ 15] local 62.40.123.106 port 48298 connected to 62.40.106.83 port 5496
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[ 15]   0.00-1.00   sec  51.8 MBytes   434 Mbits/sec    0   2.33 MBytes
[ 15]   1.00-2.00   sec   111 MBytes   933 Mbits/sec    0   3.08 MBytes
[ 15]   2.00-3.00   sec   111 MBytes   933 Mbits/sec    0   3.25 MBytes
[ 15]   3.00-4.00   sec   112 MBytes   944 Mbits/sec    0   3.25 MBytes
[ 15]   4.00-5.00   sec   111 MBytes   933 Mbits/sec    0   3.39 MBytes
[ 15]   5.00-6.00   sec   112 MBytes   944 Mbits/sec    0   3.40 MBytes
[ 15]   6.00-7.00   sec   111 MBytes   933 Mbits/sec    0   3.40 MBytes
[ 15]   7.00-8.00   sec   112 MBytes   944 Mbits/sec    0   3.42 MBytes
[ 15]   8.00-9.00   sec   102 MBytes   860 Mbits/sec    1   2.55 MBytes
[ 15]   9.00-10.00  sec   105 MBytes   881 Mbits/sec    0   2.75 MBytes

---

[ ID] Interval           Transfer     Bandwidth       Retr
[ 15]   0.00-10.00  sec  1.02 GBytes   874 Mbits/sec    1             sender
[ 15]   0.00-10.00  sec  1023 MBytes   858 Mbits/sec                  receiver

iperf Done.

SENDER END

PLEASE provide instructions on how to configure the mesh to explicitly apply the –B option in the scheduled tests of regular-testing service.

Best regards,
Ivan Garnizov

**Comment by arlake228** [comment]
There is not currently an option to set -B in regular_testing. We should add one. Marking this as 3.5.1.

**Comment by igarny** [comment]
Hi Andy,

Just wanted to hint you again on the importance of this feature, since without it we are limited on the interface configuration of the toolkit instances and we cannot make use of the pS support for multi-homed systems.
On a meeting with Antoine we were hinted by him (with regards to ls_registration service), that it should also be possible to receive a patch for the 3.4.2 release, which is also supported. Can we really rely on this?

Best regards,
Ivan

**Comment by arlake228** [comment]
We have it marked as 3.5.1 which I think is right. I'll try to make sure this is one of the first 3.5.1 issues I hit. Not sure if I will get to it before the U.S. Thanksgiving holiday next week but will try to hit it soon. I do not plan to backport it to 3.4.2. We still answer peoples questions about 3.4.2 but we don't backport feature requests like this.
